/**
 * Tests for `src/components/layout/GenerationProgressBar.tsx`.
 *
 * The progress bar is a 2px-tall wrapper with an animated indigo
 * segment. When `isStreaming` is `false` the inner `motion.div` is
 * not rendered (framer-motion's `AnimatePresence` is empty). When
 * `isStreaming` is `true` the inner `motion.div` appears.
 *
 * The component is marked `aria-hidden="true"` on the outer wrapper
 * — the active state is communicated through the chat panel's
 * status text, not this bar.
 */
import { render } from '@testing-library/react'
import { describe, expect, it } from 'vitest'

import { GenerationProgressBar } from './GenerationProgressBar'

/**
 * The animated inner block carries `bg-primary`. We assert on the
 * presence of that class (and a non-zero `style.width` or
 * `position: absolute`) to detect whether the inner bar is mounted.
 */
function innerBarMounted(container: HTMLElement): boolean {
  // The bar's inner div has w-[30%] and bg-primary. It also lives
  // inside an element that has the structure generated by
  // framer-motion. We simply look for a child of the outer wrapper
  // that has `bg-primary` in its class list.
  const wrapper = container.firstElementChild
  if (!wrapper) return false
  return wrapper.querySelector('.bg-primary') !== null
}

describe('GenerationProgressBar()', () => {
  it('test_hidden_when_not_streaming — no inner bar element when isStreaming=false', () => {
    const { container } = render(<GenerationProgressBar isStreaming={false} />)

    expect(innerBarMounted(container)).toBe(false)
  })

  it('test_visible_when_streaming — the inner bar element is mounted when isStreaming=true', () => {
    const { container } = render(<GenerationProgressBar isStreaming={true} />)

    expect(innerBarMounted(container)).toBe(true)
  })

  it('test_has_aria_label — the outer wrapper exposes an accessibility hook', () => {
    // The component is decorative (the chat status text carries the
    // "in flight" message), so it is marked `aria-hidden`. We assert
    // the attribute is present so the bar does not pollute the
    // accessibility tree, which is the contract the implementation
    // documents.
    const { container } = render(<GenerationProgressBar isStreaming={true} />)

    const wrapper = container.firstElementChild
    expect(wrapper).not.toBeNull()
    expect(wrapper?.getAttribute('aria-hidden')).toBe('true')
  })
})
